### ISSUE TITLE
[Suggestion] Exception list

### ISSUE THREAD

**Issue by happysurf** [M-Reimer/togglecookies#1]
I suggest to add the option for manage the cookies also in exception list.
Will be great make all with icon color or something like this:
- blue color = all cookies allowed;
- green color = web site in exception list:
- red color = all cookies blocked.

**Comment by M-Reimer** [comment]
Firefox has this built in. Just open your preferences. Go to "Privacy & Security". Next to "Cookies and Site Data" you'll find "Exceptions...".
It wouldn't be very useful to clone existing functionality.
Unfortunately Addons are not allowed to access this list, so I can't change the icon color based on your selection.

**Comment by happysurf** [comment]
I know, but the built in feature is not so friendly and efficient.
In any case I understand your point.
Thanks.
