### ISSUE TITLE
incompatibility with another addon

### ISSUE THREAD

**Issue by rinaldi6109** [M-Reimer/togglecookies#2]
I'm sorry, but I realized that your addon is incompatible with another one, raindrop.io, which I use more frequently. When installed, your addon works regularly but it doesn't allow to use raindrop.io as an authenticated user.

**Comment by M-Reimer** [comment]
So I think your session is saved based on a cookie.
To use "raindrop.io" you would have to enable cookies then. Disable them again after that?
I'm open to any other suggestions but to be honest, I don't use my addon myself. It is just meant as an "upgrade path" for PrefBar users and it duplicates the functionality, I once offered in PrefBar.

**Comment by rinaldi6109** [comment]
I use your addon to temporarily disable cookies, and only on a specific site. When I visit that site, I disable cookies, reload the page, and then reenable ccokies. 
So, I usually have enable cookies. But even so, raindrop.io does not work.

**Comment by M-Reimer** [comment]
You misinterpret what "Toogle Cookies" actually does.
You can't disable "cookies for one site" with it.
It always works globally.
So if you have 10 tabs with 10 different websites open, then toggling cookies off will disable it for all of them.
And, most probably the reason for your problem, it also disables cookies for other Addons as soon as you toggle them off.

**Comment by M-Reimer** [comment]
No more info. Closing. What "togglecookies" does is to toggle a Firefox built in preference. Not much I can do about how this behaves with different websites.
